sudo: false
language: python
python:
  - "3.6"
  - "3.4"
  - "2.7"
env:
  - DJANGO="Django>=1.11,<2.0"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
matrix:
  exclude:
    - env: DJANGO="Django>=2.0,<2.1"
      python: "2.7"
    - env: DJANGO="Django>=2.1,<2.2"
      python: "2.7"
    - env: DJANGO="Django>=2.1,<2.2"
      python: "3.4"

install: pip install $DJANGO
script: python setup.py test
